/*
  content-store.js
  ----------------
  Small helper shared by index.html (main.js) and admin.html (admin.js).
  Handles merging the default content (content.js) with any edits the
  user has saved in this browser (localStorage), plus export/import.
*/

(function (global) {
  const STORAGE_KEY = "bb_content_overrides_v1";

  function deepClone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function isPlainObject(value) {
    return Object.prototype.toString.call(value) === "[object Object]";
  }

  function deepMerge(base, override) {
    if (Array.isArray(base) || Array.isArray(override)) {
      return override !== undefined ? override : base;
    }
    if (isPlainObject(base) && isPlainObject(override)) {
      const result = { ...base };
      Object.keys(override).forEach((key) => {
        result[key] = deepMerge(base[key], override[key]);
      });
      return result;
    }
    return override !== undefined ? override : base;
  }

  function getOverrides() {
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      return raw ? JSON.parse(raw) : {};
    } catch (err) {
      console.warn("BB content-store: could not read overrides", err);
      return {};
    }
  }

  function setOverrides(overrides) {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(overrides));
  }

  function clearOverrides() {
    window.localStorage.removeItem(STORAGE_KEY);
  }

  function getContent() {
    const defaults = deepClone(global.DEFAULT_CONTENT || {});
    const overrides = getOverrides();
    return deepMerge(defaults, overrides);
  }

  function saveContent(fullContent) {
    setOverrides(fullContent);
  }

  function exportAsFileText(fullContent) {
    return (
      "/*\n" +
      "  content.js\n" +
      "  ----------\n" +
      "  Auto-generated by the theblackbird.ai content editor on " +
      new Date().toISOString() +
      ".\n" +
      "  Replace the existing js/content.js with this file to make your\n" +
      "  edits permanent for every visitor.\n" +
      "*/\n\n" +
      "window.DEFAULT_CONTENT = " +
      JSON.stringify(fullContent, null, 2) +
      ";\n"
    );
  }

  function downloadTextFile(filename, text) {
    const blob = new Blob([text], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  function parseImportedFileText(text) {
    const match = text.match(/window\.DEFAULT_CONTENT\s*=\s*([\s\S]*?);\s*$/);
    if (!match) {
      throw new Error(
        "Could not find `window.DEFAULT_CONTENT = {...}` in this file."
      );
    }
    return JSON.parse(match[1]);
  }

  global.BBContentStore = {
    getContent,
    saveContent,
    clearOverrides,
    getOverrides,
    exportAsFileText,
    downloadTextFile,
    parseImportedFileText,
    deepMerge,
  };
})(window);
